### ISSUE TITLE
1px 边框

### ISSUE THREAD

**Issue by onlymisaky** [onlymisaky/favorites#1]
相关文章
- https://juejin.cn/post/6844903582370643975

### 缩放
```css
.half-border {
  height: 1px;
  transform: scaleY(0.5);
  /* 防止在 chrome 中线变虚 */
  transform-origin: 50% 100%; 
}
```

### 线性渐变 linear-gradient
```css
.half-border {
  height: 1px;
  background: linear-gradient(0deg, #fff, #000);
}
```

### boxshadow
```css
.half-border {
  height: 1px;
  background: none;
  box-shadow: 0 0.5px 0 #000;
}
```

### svg
```css
.hr.svg {
  background: none;
  height: 1px;
  background: url("data:image/svg+xml;utf-8,<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='1px'><line x1='0' y1='0' x2='100%' y2='0' stroke='#000'></line></svg>");
  /* 兼容 Firefox */
  background: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScxMDAlJyBoZWlnaHQ9JzFweCc+PGxpbmUgeDE9JzAnIHkxPScwJyB4Mj0nMTAwJScgeTI9JzAnIHN0cm9rZT0nIzAwMCc+PC9saW5lPjwvc3ZnPg==");
}
```

### 修改meta
```html
<meta name="viewport" content="width=device-width,initial-sacle=0.5">
```
